version: '3.3'
services:
  tomcat:
    build: .
    container_name: tomcat
    ports:
      - "8080:8080"
    links:
      - postgres
  postgres:
    image: postgres:9.6-alpine
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mvcreactlearn